export enum SocialPostActions {
  SOCIALPOST_DATA = 'SOCIALPOST_DATA',
  SOCIALPOST_DATA_SUCCESS = 'SOCIALPOST_DATA_SUCCESS',
  SOCIALPOST_DATA_ERROR = 'SOCIALPOST_DATA_ERROR',
  SOCIALPOST_DATA_CLEAN = 'SOCIALPOST_DATA_CLEAN'
}